// <auto-generated />
using System;
using E_BookingFutsal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_BookingFutsal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("E_BookingFutsal.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoHp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("E_BookingFutsal.Models.Booking", b =>
                {
                    b.Property<int>("IdBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBooking"));

                    b.Property<int>("Durasi")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LapanganIdLapangan")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoHp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StatusIdStatus")
                        .HasColumnType("int");

                    b.Property<int>("StatusMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TglBooking")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdBooking");

                    b.HasIndex("LapanganIdLapangan");

                    b.HasIndex("StatusIdStatus");

                    b.HasIndex("StatusMemberId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("E_BookingFutsal.Models.DaftarMember", b =>
                {
                    b.Property<int>("IdMember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMember"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaMember")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoHp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMember");

                    b.ToTable("DaftarMembers");
                });

            modelBuilder.Entity("E_BookingFutsal.Models.Lapangan", b =>
                {
                    b.Property<int>("IdLapangan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLapangan"));

                    b.Property<string>("NamaLapangan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLapangan");

                    b.ToTable("Lapang");
                });

            modelBuilder.Entity("E_BookingFutsal.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusMember")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusMember = "Member"
                        },
                        new
                        {
                            Id = 2,
                            StatusMember = "Bukan Member"
                        });
                });

            modelBuilder.Entity("E_BookingFutsal.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("E_BookingFutsal.Models.Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("NamaStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdStatus");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            IdStatus = 1,
                            NamaStatus = "Diterima"
                        },
                        new
                        {
                            IdStatus = 2,
                            NamaStatus = "Ditolak"
                        });
                });

            modelBuilder.Entity("E_BookingFutsal.Models.Admin", b =>
                {
                    b.HasOne("E_BookingFutsal.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("E_BookingFutsal.Models.Booking", b =>
                {
                    b.HasOne("E_BookingFutsal.Models.Lapangan", "Lapangan")
                        .WithMany()
                        .HasForeignKey("LapanganIdLapangan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_BookingFutsal.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusIdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_BookingFutsal.Models.Member", "StatusMember")
                        .WithMany()
                        .HasForeignKey("StatusMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lapangan");

                    b.Navigation("Status");

                    b.Navigation("StatusMember");
                });
#pragma warning restore 612, 618
        }
    }
}
